spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD:postgres}
    username: ${POSTGRES_USERNAME:postgres}
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME:bank_cards_db}
  jpa:
    open-in-view: false
    show-sql: true
  liquibase:
    change-log: classpath:/db/migration/db.changelog-master.yml

server:
  port: 8080